
CREATE TABLE `room_detail`  (
   id varchar (50),
  `title` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `city` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `district` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `road` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `community` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `save_time` datetime(0) NOT NULL,
  `up_time` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `price` int(11) NOT NULL,
  `pay_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `rental_method` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `house_type` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `room_type` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `area_size` int CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `decorate_type` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `ori` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `floor_info` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `has_heat` tinyint(4) NULL DEFAULT NULL,
  `has_tv` tinyint(1) NULL DEFAULT NULL,
  `has_refrigerator` tinyint(1) NULL DEFAULT NULL,
  `has_washingMachine` tinyint(1) NULL DEFAULT NULL,
  `has_balcony` tinyint(1) NULL DEFAULT NULL,
  `has_cook` tinyint(1) NULL DEFAULT NULL,
  `has_airConditioner` tinyint(1) NULL DEFAULT NULL,
  `has_waterHeater` tinyint(1) NULL DEFAULT NULL,
  `has_bed` tinyint(1) NULL DEFAULT NULL,
  `has_wardrobe` tinyint(1) NULL DEFAULT NULL,
  `has_sofa` tinyint(1) NULL DEFAULT NULL,
  `has_toilet` tinyint(4) NULL DEFAULT NULL,
  `has_smartLock` tinyint(4) NULL DEFAULT NULL,
  `has_ventilator` tinyint(4) NULL DEFAULT NULL,
  `has_gasStove` tinyint(4) NULL DEFAULT NULL,
  `has_wifi` tinyint(1) NULL DEFAULT NULL,
  `room_num` tinyint(4) NULL DEFAULT NULL,
  `bath_num` tinyint(4) NULL DEFAULT NULL,
  `halls_num` tinyint(4) NULL DEFAULT NULL,
  `traffic` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `description` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `url` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `pic_url` varchar(5000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `pic_path` varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE = InnoDB CHARACTER SET = utf8;
