package com.oliver.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;

public class Room implements Serializable {

    public interface RoomSimpleView{}

    public interface RoomDetailView extends RoomSimpleView{};

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.id
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.title
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.city
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.district
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.road
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String road;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.community
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.save_time
     *
     * @mbggenerated
     */
    private Date saveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.up_time
     *
     * @mbggenerated
     */
    private String upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.price
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.pay_type
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.rental_method
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String rentalMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.house_type
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.room_type
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    private String roomType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.area_size
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Integer areaSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.decorate_type
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private String decorateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.ori
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private String ori;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.floor_info
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private String floorInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_heat
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasHeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_tv
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasTv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_refrigerator
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasRefrigerator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_washing_machine
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasWashingMachine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_balcony
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasBalcony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_cook
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasCook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_air_conditioner
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasAirConditioner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_water_heater
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasWaterHeater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_bed
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasBed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_wardrobe
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasWardrobe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_sofa
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasSofa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_toilet
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasToilet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_smart_lock
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasSmartLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_ventilator
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasVentilator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_gas_stove
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasGasStove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.has_wifi
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Boolean hasWifi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.room_num
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Byte roomNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.bath_num
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Byte bathNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.halls_num
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private Byte hallsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.description
     *
     * @mbggenerated
     */
    @JsonView(RoomDetailView.class)
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.url
     *
     * @mbggenerated
     */
    @JsonIgnore
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.pic_url
     *
     * @mbggenerated
     */
    /**
     * 自定义字段（在数据表基础上添加的字段）
     */
    @JsonView(RoomSimpleView.class)
    private String cover;

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    @JsonView(RoomDetailView.class)
    private ArrayList<String> image;

    public ArrayList<String> getImage() {
        return image;
    }

    public void setImage(ArrayList<String> image) {
        this.image = image;
    }

    //该房源被浏览时间
    @JsonFormat
    private Date browseTime;

    //该房源被收藏时间
    private Date addTime;

    public Date getBrowseTime() {
        return browseTime;
    }

    public void setBrowseTime(Date browseTime) {
        this.browseTime = browseTime;
    }

    public Date getAddTime() {
        return addTime;
    }

    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.pic_path
     *
     * @mbggenerated
     */
    @JsonIgnore
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house..room.traffic
     *
     * @mbggenerated
     */
    private String traffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table house..room
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.id
     *
     * @return the value of house..room.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.id
     *
     * @param id the value for house..room.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.title
     *
     * @return the value of house..room.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.title
     *
     * @param title the value for house..room.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.city
     *
     * @return the value of house..room.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.city
     *
     * @param city the value for house..room.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.district
     *
     * @return the value of house..room.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.district
     *
     * @param district the value for house..room.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.road
     *
     * @return the value of house..room.road
     *
     * @mbggenerated
     */
    public String getRoad() {
        return road;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.road
     *
     * @param road the value for house..room.road
     *
     * @mbggenerated
     */
    public void setRoad(String road) {
        this.road = road == null ? null : road.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.community
     *
     * @return the value of house..room.community
     *
     * @mbggenerated
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.community
     *
     * @param community the value for house..room.community
     *
     * @mbggenerated
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.save_time
     *
     * @return the value of house..room.save_time
     *
     * @mbggenerated
     */
    public Date getSaveTime() {
        return saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.save_time
     *
     * @param saveTime the value for house..room.save_time
     *
     * @mbggenerated
     */
    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.up_time
     *
     * @return the value of house..room.up_time
     *
     * @mbggenerated
     */
    public String getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.up_time
     *
     * @param upTime the value for house..room.up_time
     *
     * @mbggenerated
     */
    public void setUpTime(String upTime) {
        this.upTime = upTime == null ? null : upTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.price
     *
     * @return the value of house..room.price
     *
     * @mbggenerated
     */

    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.price
     *
     * @param price the value for house..room.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.pay_type
     *
     * @return the value of house..room.pay_type
     *
     * @mbggenerated
     */
    @JsonView(RoomSimpleView.class)
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.pay_type
     *
     * @param payType the value for house..room.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.rental_method
     *
     * @return the value of house..room.rental_method
     *
     * @mbggenerated
     */
    public String getRentalMethod() {
        return rentalMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.rental_method
     *
     * @param rentalMethod the value for house..room.rental_method
     *
     * @mbggenerated
     */
    public void setRentalMethod(String rentalMethod) {
        this.rentalMethod = rentalMethod == null ? null : rentalMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.house_type
     *
     * @return the value of house..room.house_type
     *
     * @mbggenerated
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.house_type
     *
     * @param houseType the value for house..room.house_type
     *
     * @mbggenerated
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.room_type
     *
     * @return the value of house..room.room_type
     *
     * @mbggenerated
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.room_type
     *
     * @param roomType the value for house..room.room_type
     *
     * @mbggenerated
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType == null ? null : roomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.area_size
     *
     * @return the value of house..room.area_size
     *
     * @mbggenerated
     */
    public Integer getAreaSize() {
        return areaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.area_size
     *
     * @param areaSize the value for house..room.area_size
     *
     * @mbggenerated
     */
    public void setAreaSize(Integer areaSize) {
        this.areaSize = areaSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.decorate_type
     *
     * @return the value of house..room.decorate_type
     *
     * @mbggenerated
     */
    public String getDecorateType() {
        return decorateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.decorate_type
     *
     * @param decorateType the value for house..room.decorate_type
     *
     * @mbggenerated
     */
    public void setDecorateType(String decorateType) {
        this.decorateType = decorateType == null ? null : decorateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.ori
     *
     * @return the value of house..room.ori
     *
     * @mbggenerated
     */
    public String getOri() {
        return ori;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.ori
     *
     * @param ori the value for house..room.ori
     *
     * @mbggenerated
     */
    public void setOri(String ori) {
        this.ori = ori == null ? null : ori.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.floor_info
     *
     * @return the value of house..room.floor_info
     *
     * @mbggenerated
     */
    public String getFloorInfo() {
        return floorInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.floor_info
     *
     * @param floorInfo the value for house..room.floor_info
     *
     * @mbggenerated
     */
    public void setFloorInfo(String floorInfo) {
        this.floorInfo = floorInfo == null ? null : floorInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_heat
     *
     * @return the value of house..room.has_heat
     *
     * @mbggenerated
     */
    public Boolean getHasHeat() {
        return hasHeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_heat
     *
     * @param hasHeat the value for house..room.has_heat
     *
     * @mbggenerated
     */
    public void setHasHeat(Boolean hasHeat) {
        this.hasHeat = hasHeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_tv
     *
     * @return the value of house..room.has_tv
     *
     * @mbggenerated
     */
    public Boolean getHasTv() {
        return hasTv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_tv
     *
     * @param hasTv the value for house..room.has_tv
     *
     * @mbggenerated
     */
    public void setHasTv(Boolean hasTv) {
        this.hasTv = hasTv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_refrigerator
     *
     * @return the value of house..room.has_refrigerator
     *
     * @mbggenerated
     */
    public Boolean getHasRefrigerator() {
        return hasRefrigerator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_refrigerator
     *
     * @param hasRefrigerator the value for house..room.has_refrigerator
     *
     * @mbggenerated
     */
    public void setHasRefrigerator(Boolean hasRefrigerator) {
        this.hasRefrigerator = hasRefrigerator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_washing_machine
     *
     * @return the value of house..room.has_washing_machine
     *
     * @mbggenerated
     */
    public Boolean getHasWashingMachine() {
        return hasWashingMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_washing_machine
     *
     * @param hasWashingMachine the value for house..room.has_washing_machine
     *
     * @mbggenerated
     */
    public void setHasWashingMachine(Boolean hasWashingMachine) {
        this.hasWashingMachine = hasWashingMachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_balcony
     *
     * @return the value of house..room.has_balcony
     *
     * @mbggenerated
     */
    public Boolean getHasBalcony() {
        return hasBalcony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_balcony
     *
     * @param hasBalcony the value for house..room.has_balcony
     *
     * @mbggenerated
     */
    public void setHasBalcony(Boolean hasBalcony) {
        this.hasBalcony = hasBalcony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_cook
     *
     * @return the value of house..room.has_cook
     *
     * @mbggenerated
     */
    public Boolean getHasCook() {
        return hasCook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_cook
     *
     * @param hasCook the value for house..room.has_cook
     *
     * @mbggenerated
     */
    public void setHasCook(Boolean hasCook) {
        this.hasCook = hasCook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_air_conditioner
     *
     * @return the value of house..room.has_air_conditioner
     *
     * @mbggenerated
     */
    public Boolean getHasAirConditioner() {
        return hasAirConditioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_air_conditioner
     *
     * @param hasAirConditioner the value for house..room.has_air_conditioner
     *
     * @mbggenerated
     */
    public void setHasAirConditioner(Boolean hasAirConditioner) {
        this.hasAirConditioner = hasAirConditioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_water_heater
     *
     * @return the value of house..room.has_water_heater
     *
     * @mbggenerated
     */
    public Boolean getHasWaterHeater() {
        return hasWaterHeater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_water_heater
     *
     * @param hasWaterHeater the value for house..room.has_water_heater
     *
     * @mbggenerated
     */
    public void setHasWaterHeater(Boolean hasWaterHeater) {
        this.hasWaterHeater = hasWaterHeater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_bed
     *
     * @return the value of house..room.has_bed
     *
     * @mbggenerated
     */
    public Boolean getHasBed() {
        return hasBed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_bed
     *
     * @param hasBed the value for house..room.has_bed
     *
     * @mbggenerated
     */
    public void setHasBed(Boolean hasBed) {
        this.hasBed = hasBed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_wardrobe
     *
     * @return the value of house..room.has_wardrobe
     *
     * @mbggenerated
     */
    public Boolean getHasWardrobe() {
        return hasWardrobe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_wardrobe
     *
     * @param hasWardrobe the value for house..room.has_wardrobe
     *
     * @mbggenerated
     */
    public void setHasWardrobe(Boolean hasWardrobe) {
        this.hasWardrobe = hasWardrobe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_sofa
     *
     * @return the value of house..room.has_sofa
     *
     * @mbggenerated
     */
    public Boolean getHasSofa() {
        return hasSofa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_sofa
     *
     * @param hasSofa the value for house..room.has_sofa
     *
     * @mbggenerated
     */
    public void setHasSofa(Boolean hasSofa) {
        this.hasSofa = hasSofa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_toilet
     *
     * @return the value of house..room.has_toilet
     *
     * @mbggenerated
     */
    public Boolean getHasToilet() {
        return hasToilet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_toilet
     *
     * @param hasToilet the value for house..room.has_toilet
     *
     * @mbggenerated
     */
    public void setHasToilet(Boolean hasToilet) {
        this.hasToilet = hasToilet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_smart_lock
     *
     * @return the value of house..room.has_smart_lock
     *
     * @mbggenerated
     */
    public Boolean getHasSmartLock() {
        return hasSmartLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_smart_lock
     *
     * @param hasSmartLock the value for house..room.has_smart_lock
     *
     * @mbggenerated
     */
    public void setHasSmartLock(Boolean hasSmartLock) {
        this.hasSmartLock = hasSmartLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_ventilator
     *
     * @return the value of house..room.has_ventilator
     *
     * @mbggenerated
     */
    public Boolean getHasVentilator() {
        return hasVentilator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_ventilator
     *
     * @param hasVentilator the value for house..room.has_ventilator
     *
     * @mbggenerated
     */
    public void setHasVentilator(Boolean hasVentilator) {
        this.hasVentilator = hasVentilator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_gas_stove
     *
     * @return the value of house..room.has_gas_stove
     *
     * @mbggenerated
     */
    public Boolean getHasGasStove() {
        return hasGasStove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_gas_stove
     *
     * @param hasGasStove the value for house..room.has_gas_stove
     *
     * @mbggenerated
     */
    public void setHasGasStove(Boolean hasGasStove) {
        this.hasGasStove = hasGasStove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.has_wifi
     *
     * @return the value of house..room.has_wifi
     *
     * @mbggenerated
     */
    public Boolean getHasWifi() {
        return hasWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.has_wifi
     *
     * @param hasWifi the value for house..room.has_wifi
     *
     * @mbggenerated
     */
    public void setHasWifi(Boolean hasWifi) {
        this.hasWifi = hasWifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.room_num
     *
     * @return the value of house..room.room_num
     *
     * @mbggenerated
     */
    public Byte getRoomNum() {
        return roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.room_num
     *
     * @param roomNum the value for house..room.room_num
     *
     * @mbggenerated
     */
    public void setRoomNum(Byte roomNum) {
        this.roomNum = roomNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.bath_num
     *
     * @return the value of house..room.bath_num
     *
     * @mbggenerated
     */
    public Byte getBathNum() {
        return bathNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.bath_num
     *
     * @param bathNum the value for house..room.bath_num
     *
     * @mbggenerated
     */
    public void setBathNum(Byte bathNum) {
        this.bathNum = bathNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.halls_num
     *
     * @return the value of house..room.halls_num
     *
     * @mbggenerated
     */
    public Byte getHallsNum() {
        return hallsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.halls_num
     *
     * @param hallsNum the value for house..room.halls_num
     *
     * @mbggenerated
     */
    public void setHallsNum(Byte hallsNum) {
        this.hallsNum = hallsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.description
     *
     * @return the value of house..room.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.description
     *
     * @param description the value for house..room.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.url
     *
     * @return the value of house..room.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.url
     *
     * @param url the value for house..room.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.pic_url
     *
     * @return the value of house..room.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.pic_url
     *
     * @param picUrl the value for house..room.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.pic_path
     *
     * @return the value of house..room.pic_path
     *
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.pic_path
     *
     * @param picPath the value for house..room.pic_path
     *
     * @mbggenerated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house..room.traffic
     *
     * @return the value of house..room.traffic
     *
     * @mbggenerated
     */
    public String getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house..room.traffic
     *
     * @param traffic the value for house..room.traffic
     *
     * @mbggenerated
     */
    public void setTraffic(String traffic) {
        this.traffic = traffic == null ? null : traffic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house..room
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", city=").append(city);
        sb.append(", district=").append(district);
        sb.append(", road=").append(road);
        sb.append(", community=").append(community);
        sb.append(", saveTime=").append(saveTime);
        sb.append(", upTime=").append(upTime);
        sb.append(", price=").append(price);
        sb.append(", payType=").append(payType);
        sb.append(", rentalMethod=").append(rentalMethod);
        sb.append(", houseType=").append(houseType);
        sb.append(", roomType=").append(roomType);
        sb.append(", areaSize=").append(areaSize);
        sb.append(", decorateType=").append(decorateType);
        sb.append(", ori=").append(ori);
        sb.append(", floorInfo=").append(floorInfo);
        sb.append(", hasHeat=").append(hasHeat);
        sb.append(", hasTv=").append(hasTv);
        sb.append(", hasRefrigerator=").append(hasRefrigerator);
        sb.append(", hasWashingMachine=").append(hasWashingMachine);
        sb.append(", hasBalcony=").append(hasBalcony);
        sb.append(", hasCook=").append(hasCook);
        sb.append(", hasAirConditioner=").append(hasAirConditioner);
        sb.append(", hasWaterHeater=").append(hasWaterHeater);
        sb.append(", hasBed=").append(hasBed);
        sb.append(", hasWardrobe=").append(hasWardrobe);
        sb.append(", hasSofa=").append(hasSofa);
        sb.append(", hasToilet=").append(hasToilet);
        sb.append(", hasSmartLock=").append(hasSmartLock);
        sb.append(", hasVentilator=").append(hasVentilator);
        sb.append(", hasGasStove=").append(hasGasStove);
        sb.append(", hasWifi=").append(hasWifi);
        sb.append(", roomNum=").append(roomNum);
        sb.append(", bathNum=").append(bathNum);
        sb.append(", hallsNum=").append(hallsNum);
        sb.append(", description=").append(description);
        sb.append(", url=").append(url);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", picPath=").append(picPath);
        sb.append(", traffic=").append(traffic);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}